# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\boardWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import cv2
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QAction

from model.Board_m import Board
from model.ImageIO import ImageIO


class Ui_Board(object):
    canvas_border = 25

    def __init__(self, image_io: ImageIO, board_data: Board):
        super().__init__()

        self.image_io = image_io
        self.board_data = board_data

    def setupUi(self, Board):
        Board.setObjectName("Board")
        Board.resize(838, 619)
        self.centralwidget = QtWidgets.QWidget(Board)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.boardCanvas = QtWidgets.QLabel(self.centralwidget)
        self.boardCanvas.setText("")
        self.boardCanvas.setPixmap(QtGui.QPixmap("\images.png"))
        self.boardCanvas.setScaledContents(False)
        self.boardCanvas.setObjectName("boardCanvas")
        self.gridLayout.addWidget(self.boardCanvas, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 2, 1, 1, 1)
        Board.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Board)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 838, 26))
        self.menubar.setObjectName("menubar")
        Board.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Board)
        self.statusbar.setObjectName("statusbar")
        Board.setStatusBar(self.statusbar)

        self.retranslateUi(Board)
        QtCore.QMetaObject.connectSlotsByName(Board)

        '''______________'''

        #self.menu =

        '''______________'''

    def retranslateUi(self, Board):
        _translate = QtCore.QCoreApplication.translate
        Board.setWindowTitle(_translate("Board", "MainWindow"))

    def update_board(self):
        cv_img = self.image_io.lastImage
        board_lines = self.board_data.canvas
        cv_img = cv2.add(board_lines, cv_img)


        if cv_img is None:
            return

        qt_img = self.convert_cv_qt(cv_img, self.centralwidget.width(), self.centralwidget.height())

        self.boardCanvas.setPixmap(qt_img)


    def convert_cv_qt(self, cv_img, area_w, area_h):
        rgb_image = cv2.cvtColor(cv_img, cv2.COLOR_BGR2RGB)
        h, w, ch = rgb_image.shape
        bytes_per_line = ch * w
        convert_to_Qt_format = QtGui.QImage(rgb_image.data, w, h, bytes_per_line, QtGui.QImage.Format_RGB888)

        qt_img_w = area_w - self.canvas_border
        qt_img_h = area_h - self.canvas_border
        p = convert_to_Qt_format.scaled(qt_img_w, qt_img_h, Qt.KeepAspectRatio)

        return QPixmap.fromImage(p)